# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: stageA
    displayName: 'This is stage A'
    jobs:
      - job: jobA
      
  - stage: stageB
    displayName: 'This is stage B'
    jobs:
      - job: jobB

  - stage: stageC
    displayName: 'This is stage C'
    jobs:
      - job: jobC

  - stage: stageD
    displayName: 'This is stage D'
    jobs:
      - job: jobD
