# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

#trigger:
#- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Dev
    jobs:
      - job: DevJob
        steps:
        - task: ManualValidation@0
          displayName: 'Manual Validation'
          inputs:
            notifyUsers: 'vincent.m.pantia@gmail.com'
            instructions: 'To resume you must review and approve this process.'
            onTimeout: reject

  - stage: QA
    dependsOn: Dev
    condition: succeeded('Dev')
    jobs:
      - job: QAJob

  - stage: UAT
    dependsOn: Dev
    condition: succeeded('Dev')
    jobs:
      - job: UATJob
    
  - stage: PROD
    dependsOn:
      - QA
      - UAT
    condition: succeeded('QA', 'UAT')
    jobs:
      - job: PRODJob

#  - stage: stageC
#    displayName: 'This is stage C'
#    jobs:
#      - job: jobC

#  - stage: stageD
#    displayName: 'This is stage D'
#    jobs:
#      - job: jobD
